### PR TITLE
Override the `@solana/web3.js` transitive dependency of `spl-token` and `buffer-layout-utils` in a more targeted way

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by steveluscher** [comment]
* **#2817** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2817?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2816** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2816?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2815** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2815?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mcintyre94 — APPROVED** [review]
Looks fine! What's the reason for this out of interest?

**Comment by buffalojoec** [comment]
> Looks fine! What's the reason for this out of interest?

Agreed, where are we even using these libraries? The nice thing is this _shouldn't_ ever break considering legacy will never reach 2.0!

**Comment by steveluscher** [comment]
OMG the reason is so dumb; it's because we use `@solana/spl-token` to create token accounts for the `connection.test.ts` in the legacy library.

Know what. I'm just going to replace those with test fixtures.

**Comment by steveluscher** [comment]
Abandoning this in favour of https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2821/Rewrite-the-legacy-token-tests-without-solana-spl-token

**Pull request closed without merging**
