### PR TITLE
chore: create custom publish strategy for legacy packages

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

Here we add a `prepare` step to the release script for the legacy library.

1. Build all of the dependencies (right now just `@solana/ed25519`)
2. Versiona and publish all of the dependencies to npm
3. Publish `@solana/web3.js` with all of those versions baked in

In doing so, _all_ of the legacy packages version together.

NOTE: If, for whatever reason, you run this locally, don't commit the result. It leaves changes in your working copy.

### CODE REVIEW

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1928** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1928?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1929** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1929?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1930** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1930?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1931** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1931?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1932** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1932?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1932?utm_source=stack-comment).

**Review by lorisleiva — APPROVED** [review]
It would be nice to use changeset for this in the future. We can set it up so that all legacy libraries are published together whereas the new libraries can simply be linked together.

**Comment by steveluscher** [comment]
Totally. This was the smallest change I could make not to rock the boat too much, and even still it took me a week and like 20 hours of reading conventional changelog code to be able to do.

I think when we move to something else we're going to have a real, serious problem with the way that I've put multiple npm packages with the same name in the same workspace. I do this because I want to be able to pull modern packages into legacy and have them build with workspaces, but release management software is going to hate that. Gonna be a nightmare.

**Comment by buffalojoec** [comment]
> I think when we move to something else we're going to have a real, serious problem with the way that I've put multiple npm packages with the same name in the same workspace. I do this because I want to be able to pull modern packages into legacy and have them build with workspaces, but release management software is going to hate that. Gonna be a nightmare.

Ummm, is this something we can ice now before it swells?

We definitely don't want dependency problems with JS out of the gate, considering the hell v1.16 put devs through on the Rust side of things. If dependency management, dependabot, `yarn upgrade`, etc. are shaky on/after release we are _toast_.

**Comment by lorisleiva** [comment]
@steveluscher Changeset should work fine with multiple packages in the same namespace as long as they are all part of the same folder or explicitly whitelisted. What sort of issues do you anticipate?

**Comment by steveluscher** [comment]
* The workspace will puke if there are two packages named `@solana/keys` (_maybe_ we can hack around this with a `.pnpmfile.cjs`)
* Changesets' CI script will not know wtf to do if I call a package `@solana/keys-legacy` but expect it to be published as `@solana/keys@1.x.x`.

**Comment by lorisleiva** [comment]
Oh I see! So why don't we just not do this in the first place and use `legacy-` prefixes everywhere? 🙃

**Comment by steveluscher** [comment]
> So why don't we just not do this in the first place and use legacy- prefixes everywhere?

I would feel like a clown releasing `@solana/legacy-keys` and `@solana/keys` rather than `@solana/keys` at versions 1 and 2.

**Comment by steveluscher** [comment]
image

**Comment by lorisleiva** [comment]
The fact is we're gonna have to do that for some libraries anyway (such as `legacy-utils`).

I think it's much cleaner to have a set of packages that share a consistent naming convention then having some living under `legacy-x`, some living under the latest version of `x` and some living under the previous major version of `x` like `keys`.

I see nothing wrong with releasing `legacy-keys` for the split up legacy library and `keys` for the library we want to maintain going forward.

I'm worried we're overcomplicating things tbh.

**Pull request closed without merging**
