### PR TITLE
refactor(experimental): create @solana/rpc-subscriptions package

### PR DESCRIPTION
**Pull request by lorisleiva**
Similarly to the previous PR, this PR creates the top-level `@solana/rpc-subscriptions` package.
- It re-exports `@solana/rpc-subscriptions-api` and `@solana/rpc-subscriptions-spec`.
- It introduces the concepts of Clustered `RpcSubscriptions` and `RpcSubscriptionsApis`.
- It provides the `createDefaultRpcSubscriptionsTransport` function.
- It provides the `createSolanaRpcSubscriptions` function.

Here as well some of the `RpcSubscriptionsTransport` decorators could be extracted into their own packages in future PRs.

RPC packages reshuffle@2x (11)

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2154?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#2155** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2155?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2154** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2154?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2153** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2152** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2152?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2151** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2151?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2150** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2148** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2147** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2146** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2145** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2144** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2154?utm_source=stack-comment).

**Review by buffalojoec — COMMENTED** [review]
Hmmm, I'm still on the side of [my comment here](https://github.com/solana-labs/solana-web3.js/pull/2153#issuecomment-1958675355), but the `Iterable` and `Autopinging` stuff is quite complex and could be useful as tooling to customize transports via `@solana/rpc-subscriptions-transport-websocket`.

Thoughts on `@solana/rpc-subscriptions-transport-tools` (insert a better name)?

**Comment by lorisleiva** [comment]
@buffalojoec 1000%! That's what I mean in the PR description when I say "extract transport decorators". We can now easily start to break this down even further and provide more reusable and composable transports.

**Comment by lorisleiva** [comment]
✅ This PR was merged as part of https://github.com/solana-labs/solana-web3.js/pull/2168.

**Pull request closed without merging**
