### PR TITLE
refactor(experimental): create @solana/rpc-subscriptions-transport-websocket package

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR extract the WebSockets implementation of the `RpcSubscriptionsTransport` into its own package.

Similarly to [the previous PR](#2147), it does not include any Solana-specific types or helpers such as `ClusterUrl`.

RPC packages reshuffle@2x (5)

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#2148** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2147** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2146** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2145** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2144** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment).

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Review by buffalojoec — APPROVED** [review]
web

**Comment by lorisleiva** [comment]
✅ This PR was merged as part of https://github.com/solana-labs/solana-web3.js/pull/2168.

**Pull request closed without merging**
