### PR TITLE
refactor(experimental): move transport types out of rpc-transport

### PR DESCRIPTION
**Pull request by buffalojoec**
Slides the RPC Transport types into `@solana/rpc-types`.

### CODE REVIEW

**Comment by buffalojoec** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2085?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #2084** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2084?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #2085** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2085?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #2053** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2053?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #2054** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2054?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #2055** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2055?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
            * **PR #2056** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2056?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
              * **PR #2057** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2057?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
                * **PR #2058** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2058?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2085?utm_source=stack-comment).

**Comment by lorisleiva** [comment]
@buffalojoec What's the rational behind this change? From an outsiders point of view, it feels like `IRpcTransport` fits better inside `@solana/rpc-transports`. Is that type needed elsewhere?

**Comment by buffalojoec** [comment]
> @buffalojoec What's the rational behind this change? From an outsiders point of view, it feels like `IRpcTransport` fits better inside `@solana/rpc-transports`. Is that type needed elsewhere?

It gets used by `rpc-core` and `library` later in the stack, but I was kind of torn on this change as well. If you think it still belongs in `rpc-transport` I'm OK with that, but we'd also need to include the other companion types introduced in the next commit, ie. `IIRpcTransport`, `IRpcTransportDevnet`, etc.

**Comment by lorisleiva** [comment]
Hmm yeah I've checked the whole stack and I still can't see what prevents us from keeping these transport types into the transport package. Both `rpc-core` and `library` already depend on `rpc-transports` so it shouldn't be an issue.

**Pull request closed without merging**
