### PR TITLE
refactor(experimental): create @solana/rpc package

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR creates the top-level `@solana/rpc` package that glues everything together for the end-user.
- It re-exports `@solana/rpc-api` and `@solana/rpc-spec`.
- It introduces the concepts of Clustered `Rpcs` and `RpcApis`.
- It provides the `createDefaultRpcTransport` function.
- It provides the `createSolanaRpc` function (which could be updated in a future PR to only accepts a `ClusterUrl`).

Note that future PRs could export some of the transport decorators (such as request coalescing) into dedicated packages (such as `@solana/rpc-transport-request-coalescing`).

RPC packages reshuffle@2x (10)

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2153?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#2153** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2153?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2152** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2152?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2151** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2151?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2150** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2148** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2147** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2146** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2145** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2144** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2153?utm_source=stack-comment).

**Comment by steveluscher** [comment]
I can't quite put my finger on it, but to the extent that `packages/library/` is supposed to be where all the opinionated config goes (ie. this is how you build the ‘right’ RPC) I'm not sure that things like `createDefaultRpcTransport()` or `DEFAULT_RPC_CONFIG` belong here.

I'm envisioning a separation where the subpackages contain the primitives to construct the ‘default’ RPC as we know it today, and `packages/library/` has to work _just as hard_ to build the default RPC as someone would if they were designing their own custom RPC.

**Comment by lorisleiva** [comment]
@steveluscher What if someone just wants the opinionated RPC stuff from `library` but none of the rest of it?

**Comment by steveluscher** [comment]
I'll leave it up to you, but consider this use case:

Imagine that we were still going to rebuild the old web3.js with these internals. The reason that I had injectable integer overflow handling in this code is because:

* the new web3.js
  * should throw on integer overflows to prevent unspecified behaviour
  * should default to `confirmed` commitment
* the old web3.js
  * _can't_ throw on integer overflows, because to throw would be a breaking change
  * must continue to default to `finalized` commitment, because to do otherwise would be a breaking change

However you organize the code, organize it to make those two consumers' use cases happy.

**Comment by lorisleiva** [comment]
Surely the new code layout makes this better right? You could simply import the `createSolanaRpcApi` function from `@solana/rpc-api` like so:

```ts
createSolanaRpcApi<MyApi>(myCustomConfig);
```

**Comment by steveluscher** [comment]
You totally can, and build up your own transport. I expected that `packages/library/` would have to do exactly that, and apply all of the defaults, rather than the defaults being enshrined in `@solana/rpc`.

¯\\_(°ペ)\_/¯

**Comment by buffalojoec** [comment]
> You totally can, and build up your own transport. I expected that `packages/library/` would have to do exactly that, and apply all of the defaults, rather than the defaults being enshrined in `@solana/rpc`.
> 
> ¯\_(°ペ)_/¯

It seems to me that the intention here is that someone who wants to create a generic/custom RPC client would instead use the lower-level pieces (ie. `@solana/rpc-http-transport` & `@solana/rpc-spec`), and provide their own API and transformers. In the case of legacy web3.js, it would leverage `@solana/rpc-api` and then provide its own transformers.

To me, it would make sense to have something like `@solana/rpc-legacy-compat` (or whatever) to do exactly that for legacy web3.js.

Considering this is supposed to be the new Solana RPC client, with all the bells & whistles, to be used on its own or re-exported from `library`, it makes sense to me.

**Review by buffalojoec — APPROVED** [review]

**Comment by lorisleiva** [comment]
✅ This PR was merged as part of https://github.com/solana-labs/solana-web3.js/pull/2168.

**Pull request closed without merging**
